name: Go

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2.0.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod vendor

      - name: Build core
        run: make

      - name: Build C++ static lib
        run: make desktop
      - name: Remove Unused
        run: |
          pwd \;
          ls \;          
      - uses: actions/upload-artifact@v2
        with:
          name: Release
          path: app/build/bin
